#  spring:
#      jpa:
#          database: MYSQL
#          hibernate:
#              ddl-auto: validate
#          properties:
#              hibernate:
#                  dialect: org.hibernate.dialect.MySQLDialect
#
#      datasource:
#          url: jdbc:mysql://kaxudb.cemekexpp71y.ap-southeast-1.rds.amazonaws.com:3305/kaxudb
#          username: kaxudodo
#          password: kaxudodo
#          driver-classes-name: com.mysql.jdbc.Driver

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.cc: DEBUG

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user